export const pet_items ={
    "all_pet_items":{
        "PET_ITEM_FISHING_SKILL_BOOST_COMMON": "Gives +20% pet exp for Fishing",
        "PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON": "Gives +30% pet exp for Fishing",
        "PET_ITEM_FISHING_SKILL_BOOST_RARE": "Gives +40% pet exp for Fishing",
        "PET_ITEM_FISHING_SKILL_BOOST_EPIC": "Gives +50% pet exp for Fishing",
        "PET_ITEM_MINING_SKILL_BOOST_COMMON": "Gives +20% pet exp for Mining.",
        "PET_ITEM_MINING_SKILL_BOOST_RARE": "Gives +40% pet exp for Mining.",
        "PET_ITEM_COMBAT_SKILL_BOOST_COMMON": "Gives +20% pet exp for Combat.",
        "PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON": "Gives +30% pet exp for Combat.",
        "PET_ITEM_COMBAT_SKILL_BOOST_RARE": "Gives +40% pet exp for Combat.",
        "PET_ITEM_COMBAT_SKILL_BOOST_EPIC": "Gives +50% pet exp for Combat.",
        "PET_ITEM_FARMING_SKILL_BOOST_COMMON": "Gives +20% pet exp for Farming.",
        "PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON": "Gives +30% pet exp for Farming.",
        "PET_ITEM_FARMING_SKILL_BOOST_RARE": "Gives +40% pet exp for Farming.",
        "PET_ITEM_FARMING_SKILL_BOOST_EPIC": "Gives +50% pet exp for Farming.",
        "PET_ITEM_FORAGING_SKILL_BOOST_COMMON": "Gives +20% pet exp for Foraging.",
        "PET_ITEM_FORAGING_SKILL_BOOST_EPIC": "Gives +50% pet exp for Foraging.",
        "PET_ITEM_ALL_SKILLS_BOOST_COMMON": "Gives +10% pet exp for all skills",
        "PET_ITEM_EXP_SHARE": "While unequipped this pet gains 25% of the equipped pet's xp, this is split between all pets holding the item.",
        "MINOS_RELIC": "Increases all pet stats by 33.3%",
        "PET_ITEM_SPOOKY_CUPCAKE": "Increases ❁ Strength by 30 and ✦ Speed by 20",
        "PET_ITEM_BUBBLEGUM": "Bubblegum can be applied to a pet, when applied it increases the duration of Power Orbs by 2x.",
        "DWARF_TURTLE_SHELMET": "Makes the pet's owner immune to knockback.",
        "WASHED_UP_SOUVENIR": "Increases α Sea Creature Chance by 5",
        "CROCHET_TIGER_PLUSHIE": "Increases ⚔ Bonus Attack Speed by 35",
        "PET_ITEM_LUCKY_CLOVER": "Increases ✯ Magic Find by 7",
        "PET_ITEM_VAMPIRE_FANG": "Upgrades a Bat pet from Legendary to Mythic adding a bonus perk and bonus stats!",
        "PET_ITEM_TOY_JERRY": "Upgrades a Jerry pet from Legendary to Mythic and granting it a new perk!",
        "ANTIQUE_REMEDIES": "Increases the pet's ❁ Strength by 80%",
        "PET_ITEM_QUICK_CLAW": "Every 2 pet levels, you gain +1⛏ Mining Speed and +1☘ Mining Fortune",
        "PET_ITEM_TEXTBOOK": "Increases the pet's ✎ Intelligence by 100%",
        "PET_ITEM_TIER_BOOST": "Boosts the rarity of your pet by 1 tier!",
        "PET_ITEM_SADDLE": "Increase horse speed by 50% and jump boost by 100%",
        "PET_ITEM_FLYING_PIG": "Grants your pig pet the ability to fly while on your private island! You also don't need to hold a carrot on a stick to control your pig.",
    },
    "pet_item_name": [
        "PET_ITEM_FISHING_SKILL_BOOST_COMMON",
        "PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON",
        "PET_ITEM_FISHING_SKILL_BOOST_RARE",
        "PET_ITEM_FISHING_SKILL_BOOST_EPIC",
        "PET_ITEM_MINING_SKILL_BOOST_COMMON",
        "PET_ITEM_MINING_SKILL_BOOST_RARE",
        "PET_ITEM_COMBAT_SKILL_BOOST_COMMON",
        "PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON",
        "PET_ITEM_COMBAT_SKILL_BOOST_RARE",
        "PET_ITEM_COMBAT_SKILL_BOOST_EPIC",
        "PET_ITEM_FARMING_SKILL_BOOST_COMMON",
        "PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON",
        "PET_ITEM_FARMING_SKILL_BOOST_RARE",
        "PET_ITEM_FARMING_SKILL_BOOST_EPIC",
        "PET_ITEM_FORAGING_SKILL_BOOST_COMMON",
        "PET_ITEM_FORAGING_SKILL_BOOST_EPIC",
        "PET_ITEM_ALL_SKILLS_BOOST_COMMON",
        "PET_ITEM_EXP_SHARE",
        "MINOS_RELIC",
        "PET_ITEM_SPOOKY_CUPCAKE",
        "PET_ITEM_BUBBLEGUM",
        "DWARF_TURTLE_SHELMET",
        "WASHED_UP_SOUVENIR",
        "CROCHET_TIGER_PLUSHIE",
        "PET_ITEM_LUCKY_CLOVER",
        "PET_ITEM_VAMPIRE_FANG",
        "PET_ITEM_TOY_JERRY",
        "ANTIQUE_REMEDIES",
        "PET_ITEM_QUICK_CLAW",
        "PET_ITEM_TEXTBOOK",
        "PET_ITEM_TIER_BOOST",
        "PET_ITEM_SADDLE",
        "PET_ITEM_FLYING_PIG"
    ],
    "pet_item_rarity":{
        "PET_ITEM_FISHING_SKILL_BOOST_COMMON": "COMMON",
        "PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON": "UNCOMMON",
        "PET_ITEM_FISHING_SKILL_BOOST_RARE": "RARE",
        "PET_ITEM_FISHING_SKILL_BOOST_EPIC": "EPIC",
        "PET_ITEM_MINING_SKILL_BOOST_COMMON": "COMMON",
        "PET_ITEM_MINING_SKILL_BOOST_RARE": "RARE",
        "PET_ITEM_COMBAT_SKILL_BOOST_COMMON": "COMMON",
        "PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON": "UNCOMMON",
        "PET_ITEM_COMBAT_SKILL_BOOST_RARE": "RARE",
        "PET_ITEM_COMBAT_SKILL_BOOST_EPIC": "EPIC",
        "PET_ITEM_FARMING_SKILL_BOOST_COMMON": "COMMON",
        "PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON": "UNCOMMON",
        "PET_ITEM_FARMING_SKILL_BOOST_RARE": "RARE",
        "PET_ITEM_FARMING_SKILL_BOOST_EPIC": "EPIC",
        "PET_ITEM_FORAGING_SKILL_BOOST_COMMON": "COMMON",
        "PET_ITEM_FORAGING_SKILL_BOOST_EPIC": "EPIC",
        "PET_ITEM_ALL_SKILLS_BOOST_COMMON": "COMMON",
        "PET_ITEM_EXP_SHARE": "EPIC",
        "MINOS_RELIC": "EPIC",
        "PET_ITEM_SPOOKY_CUPCAKE": "UNCOMMON",
        "PET_ITEM_BUBBLEGUM": "RARE",
        "DWARF_TURTLE_SHELMET": "RARE",
        "WASHED_UP_SOUVENIR": "LEGENDARY",
        "CROCHET_TIGER_PLUSHIE": "EPIC",
        "PET_ITEM_LUCKY_CLOVER": "EPIC",
        "PET_ITEM_VAMPIRE_FANG": "LEGENDARY",
        "PET_ITEM_TOY_JERRY": "LEGENDARY",
        "ANTIQUE_REMEDIES": "EPIC",
        "PET_ITEM_QUICK_CLAW": "RARE",
        "PET_ITEM_TEXTBOOK": "LEGENDARY",
        "PET_ITEM_TIER_BOOST": "LEGENDARY",
        "PET_ITEM_SADDLE": "UNCOMMON",
        "PET_ITEM_FLYING_PIG": "UNCOMMON",
    },
    "pet_item_to_name":{
        "PET_ITEM_FISHING_SKILL_BOOST_COMMON": "Fishing Exp Boost",
        "PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON": "Fishing Exp Boost",
        "PET_ITEM_FISHING_SKILL_BOOST_RARE": "Fishing Exp Boost",
        "PET_ITEM_FISHING_SKILL_BOOST_EPIC": "Fishing Exp Boost",
        "PET_ITEM_MINING_SKILL_BOOST_COMMON": "Mining Exp Boost",
        "PET_ITEM_MINING_SKILL_BOOST_RARE": "Mining Exp Boost",
        "PET_ITEM_COMBAT_SKILL_BOOST_COMMON": "Combat Exp Boost",
        "PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON": "Combat Exp Boost",
        "PET_ITEM_COMBAT_SKILL_BOOST_RARE": "Combat Exp Boost",
        "PET_ITEM_COMBAT_SKILL_BOOST_EPIC": "Combat Exp Boost",
        "PET_ITEM_FARMING_SKILL_BOOST_COMMON": "Farming Exp Boost",
        "PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON": "Farming Exp Boost",
        "PET_ITEM_FARMING_SKILL_BOOST_RARE": "Farming Exp Boost",
        "PET_ITEM_FARMING_SKILL_BOOST_EPIC": "Farming Exp Boost",
        "PET_ITEM_FORAGING_SKILL_BOOST_COMMON": "Foraging Exp Boost",
        "PET_ITEM_FORAGING_SKILL_BOOST_EPIC": "Foraging Exp Boost",
        "PET_ITEM_ALL_SKILLS_BOOST_COMMON": "All Skills Exp Boost",
        "PET_ITEM_EXP_SHARE": "Exp Share",
        "MINOS_RELIC": "Minos Relic",
        "PET_ITEM_SPOOKY_CUPCAKE": "Spooky Cupcake",
        "PET_ITEM_BUBBLEGUM": "Bubblegum",
        "DWARF_TURTLE_SHELMET": "Dwarf Turtle Shelmet",
        "WASHED_UP_SOUVENIR": "Washed-Up Souvenir",
        "CROCHET_TIGER_PLUSHIE": "Crochet Tiger Plushie",
        "PET_ITEM_LUCKY_CLOVER": "Lucky Clover",
        "PET_ITEM_VAMPIRE_FANG": "Vampire Fang",
        "PET_ITEM_TOY_JERRY": "Jerry 3D Glasses",
        "ANTIQUE_REMEDIES": "Antique Remedies",
        "PET_ITEM_QUICK_CLAW": "Quick Claw",
        "PET_ITEM_TEXTBOOK": "Textbook",
        "PET_ITEM_TIER_BOOST": "Tier Boost",
        "PET_ITEM_SADDLE": "Saddle",
        "PET_ITEM_FLYING_PIG": "Flying Pig",
    },
}