export const trophy_names = {
    "trophy_to_names":{
        "blobfish": "§fBlobfish",
        "blobfish_bronze": "§fBlobfish",
        "blobfish_silver": "§fBlobfish",
        "blobfish_gold": "§fBlobfish",
        "blobfish_diamond": "§fBlobfish",
        "lava_horse": "§9Lavahorse",
        "lava_horse_bronze": "§9Lavahorse",
        "lava_horse_silver": "§9Lavahorse",
        "lava_horse_gold": "§9Lavahorse",
        "lava_horse_diamond": "§9Lavahorse",
        "volcanic_stonefish": "§9Volcanic Stonefish",
        "volcanic_stonefish_bronze": "§9Volcanic Stonefish",
        "volcanic_stonefish_silver": "§9Volcanic Stonefish",
        "volcanic_stonefish_gold": "§9Volcanic Stonefish",
        "volcanic_stonefish_diamond": "§9Volcanic Stonefish",
        "golden_fish": "§6Golden Fish",
        "golden_fish_bronze": "§6Golden Fish",
        "golden_fish_silver": "§6Golden Fish",
        "golden_fish_gold": "§6Golden Fish",
        "golden_fish_diamond": "§6Golden Fish",
        "gusher": "§fGusher",
        "gusher_bronze": "§fGusher",
        "gusher_silver": "§fGusher",
        "gusher_gold": "§fGusher",
        "gusher_diamond": "§fGusher",
        "obfuscated_fish_1": "§fObfuscated 1",
        "obfuscated_fish_1_bronze": "§fObfuscated 1",
        "obfuscated_fish_1_silver": "§fObfuscated 1",
        "obfuscated_fish_1_gold": "§fObfuscated 1",
        "obfuscated_fish_1_diamond": "§fObfuscated 1",
        "moldfin": "§5Moldfin",
        "moldfin_bronze": "§5Moldfin",
        "moldfin_silver": "§5Moldfin",
        "moldfin_gold": "§5Moldfin",
        "moldfin_diamond": "§5Moldfin",
        "soul_fish": "§5Soul Fish",
        "soul_fish_bronze": "§5Soul Fish",
        "soul_fish_silver": "§5Soul Fish",
        "soul_fish_gold": "§5Soul Fish",
        "soul_fish_diamond": "§5Soul Fish",
        "skeleton_fish": "§5Skeleton Fish",
        "skeleton_fish_bronze": "§5Skeleton Fish",
        "skeleton_fish_silver": "§5Skeleton Fish",
        "skeleton_fish_gold": "§5Skeleton Fish",
        "skeleton_fish_diamond": "§5Skeleton Fish",
        "mana_ray": "§9Mana Ray",
        "mana_ray_bronze": "§9Mana Ray",
        "mana_ray_silver": "§9Mana Ray",
        "mana_ray_gold": "§9Mana Ray",
        "mana_ray_diamond": "§9Mana Ray",
        "flyfish": "§aFlyfish",
        "flyfish_bronze": "§aFlyfish",
        "flyfish_silver": "§aFlyfish",
        "flyfish_gold": "§aFlyfish",
        "flyfish_diamond": "§aFlyfish",
        "slugfish": "§aSlugfish",
        "slugfish_bronze": "§aSlugfish",
        "slugfish_silver": "§aSlugfish",
        "slugfish_gold": "§aSlugfish",
        "slugfish_diamond": "§aSlugfish",
        "vanille": "§9Vanille",
        "vanille_bronze": "§9Vanille",
        "vanille_silver": "§9Vanille",
        "vanille_gold": "§9Vanille",
        "vanille_diamond": "§9Vanille",
        "karate_fish": "§5Karate Fish",
        "karate_fish_bronze": "§5Karate Fish",
        "karate_fish_silver": "§5Karate Fish",
        "karate_fish_gold": "§5Karate Fish",
        "karate_fish_diamond": "§5Karate Fish",
        "steaming_hot_flounder": "§fSteaming-Hot Flounder",
        "steaming_hot_flounder_bronze": "§fSteaming-Hot Flounder",
        "steaming_hot_flounder_silver": "§fSteaming-Hot Flounder",
        "steaming_hot_flounder_gold": "§fSteaming-Hot Flounder",
        "steaming_hot_flounder_diamond": "§fSteaming-Hot Flounder",
        "sulphur_skitter": "§fSulphur Skitter",
        "sulphur_skitter_bronze": "§fSulphur Skitter",
        "sulphur_skitter_silver": "§fSulphur Skitter",
        "sulphur_skitter_gold": "§fSulphur Skitter",
        "sulphur_skitter_diamond": "§fSulphur Skitter",
        "obfuscated_fish_2": "§aObfuscated 2",
        "obfuscated_fish_2_bronze": "§aObfuscated 2",
        "obfuscated_fish_2_silver": "§aObfuscated 2",
        "obfuscated_fish_2_gold": "§aObfuscated 2",
        "obfuscated_fish_2_diamond": "§aObfuscated 2",
        "obfuscated_fish_3": "§9Obfuscated 3",
        "obfuscated_fish_3_bronze": "§9Obfuscated 3",
        "obfuscated_fish_3_silver": "§9Obfuscated 3",
        "obfuscated_fish_3_gold": "§9Obfuscated 3",
        "obfuscated_fish_3_diamond": "§9Obfuscated 3",
    },
    "trophy_fish": [
        "blobfish",
        "blobfish_bronze",
        "blobfish_silver",
        "blobfish_gold",
        "blobfish_diamond",
        "lava_horse",
        "lava_horse_bronze",
        "lava_horse_silver",
        "lava_horse_gold",
        "lava_horse_diamond",
        "volcanic_stonefish",
        "volcanic_stonefish_bronze",
        "volcanic_stonefish_silver",
        "volcanic_stonefish_gold",
        "volcanic_stonefish_diamond",
        "golden_fish",
        "golden_fish_bronze",
        "golden_fish_silver",
        "golden_fish_gold",
        "golden_fish_diamond",
        "gusher",
        "gusher_bronze",
        "gusher_silver",
        "gusher_gold",
        "gusher_diamond",
        "obfuscated_fish_1",
        "obfuscated_fish_1_bronze",
        "obfuscated_fish_1_silver",
        "obfuscated_fish_1_gold",
        "obfuscated_fish_1_diamond",
        "moldfin",
        "moldfin_bronze",
        "moldfin_silver",
        "moldfin_gold",
        "moldfin_diamond",
        "soul_fish",
        "soul_fish_bronze",
        "soul_fish_silver",
        "soul_fish_gold",
        "soul_fish_diamond",
        "skeleton_fish",
        "skeleton_fish_bronze",
        "skeleton_fish_silver",
        "skeleton_fish_gold",
        "skeleton_fish_diamond",
        "mana_ray",
        "mana_ray_bronze",
        "mana_ray_silver",
        "mana_ray_gold",
        "mana_ray_diamond",
        "flyfish",
        "flyfish_bronze",
        "flyfish_silver",
        "flyfish_gold",
        "flyfish_diamond",
        "slugfish",
        "slugfish_bronze",
        "slugfish_silver",
        "slugfish_gold",
        "slugfish_diamond",
        "vanille",
        "vanille_bronze",
        "vanille_silver",
        "vanille_gold",
        "vanille_diamond",
        "karate_fish",
        "karate_fish_bronze",
        "karate_fish_silver",
        "karate_fish_gold",
        "karate_fish_diamond",
        "steaming_hot_flounder",
        "steaming_hot_flounder_bronze",
        "steaming_hot_flounder_silver",
        "steaming_hot_flounder_gold",
        "steaming_hot_flounder_diamond",
        "sulphur_skitter",
        "sulphur_skitter_bronze",
        "sulphur_skitter_silver",
        "sulphur_skitter_gold",
        "sulphur_skitter_diamond",
        "obfuscated_fish_2",
        "obfuscated_fish_2_bronze",
        "obfuscated_fish_2_silver",
        "obfuscated_fish_2_gold",
        "obfuscated_fish_2_diamond",
        "obfuscated_fish_3",
        "obfuscated_fish_3_bronze",
        "obfuscated_fish_3_silver",
        "obfuscated_fish_3_gold",
        "obfuscated_fish_3_diamond"
    ]
}